default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: darlan
  password: nagini100

development:
  <<: *default
  database: WebCodingChallenge_api_development

test:
  <<: *default
  database: WebCodingChallenge_api_test

production:
  <<: *default
  database: WebCodingChallenge_api_production
  username: WebCodingChallenge_api
  password: <%= ENV['WEBCODINGCHALLENGE_API_DATABASE_PASSWORD'] %>
